version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot
    volumes:
      - ${HOME}/mongo/data:/data
      - ${HOME}/mongo/log:/var/log/mongodb
    command: [ "supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf" ]
    env_file:
      - .env
