---
# - hosts: localhost
#  become: yes
#  vars:
#    ansible_user: "{{ lookup('env', 'USER') }}"
#  roles:
#    - install_docker

- hosts: localhost
  become: yes
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
  become_user: "{{ ansible_user }}"
  roles:
    - run_docker_compose
